services:
    form.cwfb.available_widget_choice:
        class: Chromedia\WidgetFormBuilderBundle\Form\AvailableWidgetChoiceFieldType
        calls:
            - [setChoices, [%_cwfb.widget_selection_choices%]]
        tags:
            - { name: form.type, alias: chromedia_available_widget_choice }

    form.cwfb.chromedia_widget_attribute:
        class: Chromedia\WidgetFormBuilderBundle\Form\WidgetAttributeFieldType
        tags:
            - { name: form.type, alias: chromedia_widget_attribute }