services:

    ## the main embedded form that will be used by other forms
    form.cwfb.chromedia_widget_builder_form_type:
        class: Chromedia\WidgetFormBuilderBundle\Form\WidgetBuilderFormType
        tags:
            - { name: form.type, alias: chromedia_widget_builder_form_type }

    form.cwfb.available_widget_choice:
        class: Chromedia\WidgetFormBuilderBundle\Form\AvailableWidgetChoiceFieldType
        calls:
            - [setChoices, [%_cwfb.widget_selection_choices%]]
        tags:
            - { name: form.type, alias: chromedia_available_widget_choice }

    form.cwfb.chromedia_widget_choice:
        class: Chromedia\WidgetFormBuilderBundle\Form\WidgetChoiceFieldType
        tags:
            - { name: form.type, alias: chromedia_widget_choice }

    form.cwfb.chromedia_widget_attribute:
        class: Chromedia\WidgetFormBuilderBundle\Form\WidgetAttributeFieldType
        tags:
            - { name: form.type, alias: chromedia_widget_attribute }

    ## for chromedia_widget_builder_form_type.widget_constraints
    form.cwfb.chromedia_widget_constraint:
        class: Chromedia\WidgetFormBuilderBundle\Form\WidgetConstraintFieldType
        tags:
            - { name: form.type, alias: chromedia_widget_constraint }

    ## dropdown of available constraints
    form.cwfb.chromedia_constraint_choice:
        class: Chromedia\WidgetFormBuilderBundle\Form\ConstraintChoiceFieldType
        calls:
            - [setChoices, [%_cwfb.widget_constraint_choices%]]
        tags:
            - { name: form.type, alias: chromedia_constraint_choice }

    ## list of constraint properties
    form.cwfb.chromedia_constraint_option:
        class: Chromedia\WidgetFormBuilderBundle\Form\ConstraintPropertyFieldType
        tags:
            - { name: form.type, alias: chromedia_constraint_option }