services:
    service.cwfb.twig_extension:
        class: Chromedia\WidgetFormBuilderBundle\Twig\WidgetFormBuilderTwigExtension
        calls:
            - [setConstraintFlattenedOptions, [%_cwfb.widget_flat_constraint_options%]]
        tags:
            - { name: twig.extension }

    cwfb.field_type_factory:
        class: Chromedia\WidgetFormBuilderBundle\Service\FieldTypeFactory
        calls:
            - [setCoreFormFactory, [@form.factory]]
            - [setAvailableConstraints, [%_cwfb.widget_constraints%]]
            - [setAvailableWidgets, [%_cwfb.available_widgets%]]